version: '3.8'

services:
  vufindsolr:
    image: solr:8
    container_name: vufindsolr
    ports:
      - "8984:8983"
    volumes:
      - ./solrdata:/var/solr
    command:
      - solr-precreate
      - vufind

  vufindweb10:
    build:
      context: .
    container_name: vufindweb10
    ports:
      - "8111:80"
    volumes:
      - ./vufind:/usr/local/vufind
      - ./phpini-override.ini:/etc/php/8.1/apache2/conf.d/99-phpini-override.ini
      - ./phpini-override.ini:/etc/php/8.1/cli/conf.d/99-phpini-override.ini
      - ./apache2-foreground:/usr/bin/apache2-foreground
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - vufindsolr
